---

# All instances use the specified JBoss EAP golden image
jboss_eap_golden_image_name: 'jboss-eap-6.4.9_GI'

# Setting IP binding for all JBoss EAP instances
jboss_eap_bind_ip_address_public: "{{ ansible_eth1.ipv4.address }}"
jboss_eap_bind_ip_address_management: "{{ ansible_eth1.ipv4.address }}"
